<?php
$result="";
$errorMSG = "";
if (isset($_REQUEST['submit'])) {
	require 'phpmailer/PHPMailerAutoload.php';
	//$CustomerEmail = $_REQUEST['email'];
	$ReceverEmail =	'contact@domain.org';
	$CustomerEmail = $ReceverEmail;
    
	$CustomerName = trim($_REQUEST['name']);
	$CustomerSubject = trim($_REQUEST['subject']);
	$CustomerMessage = trim($_REQUEST['message']);
	$CustomerCity = trim($_REQUEST['city']);
	$phone = '9876543210';
    $Web_Link = 'https://www.example.com';
    
	$mail = new PHPMailer;
	//$mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP(); 
	$mail->Host="mail.domain.com";
	$mail->SMTPSecure = "tls"; 
	$mail->Port="587";
	$mail->SMTPAuth=true;
	$mail->Username="contact@domain.org";
	$mail->Password="StronPassword@123";
	$mail->setFrom($CustomerEmail,$CustomerName);
	$mail->addAddress('contact@domain.org');
	$mail->addReplyTo($CustomerEmail,$CustomerName);
	$mail->isHTML('true');
	$mail->Subject = $CustomerSubject;
	$mail->Body=
	"Dear Company Name,".
	"<br /><br />You Recived a Query for '".$p_name."' as Below...".
	"<br /><br />Customer Name : ".$CustomerName. 
	"<br />Phone : <a href='tel:+91".$phone."'>".$phone."</a>".
	"<br />Message : ".$CustomerMessage.
	"<br /><br />Note: This notification was automatically generated by ".$Web_Link.
	"";

	// redirect to success page
if ($mail->Send()){
     echo "success , Email sent to : ".$CustomerEmail; die;
    //echo "<script type='text/javascript'>alert('Success.');window.location.assign('../index.php');</script>";
} else {
    if($errorMSG == ""){
      echo "Something went wrong :("; die;
         //echo "<script type='text/javascript'>alert('Please Try Again Later.');window.location.assign('../index.php');</script>";
    } else {
        echo $errorMSG; die;
         //echo "<script type='text/javascript'>alert('Please Try Again Later.');window.location.assign('../index.php');</script>";
    }
}
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Contact Form</title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	<link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>

	<div id="page-wrap">

		<img src="images/title.gif" alt="A Nice &amp; Simple Contact Form" /><br /><br />
		<p><?= $result; ?></p>
				
		<div id="contact-area">
			
			<form method="post" action="index.php">
				<label for="Name">Name:</label>
				<input type="text" name="name" id="Name" />
				
				<label for="subject">Subject:</label>
				<input type="text" name="subject" id="subject" />

				<label for="City">City:</label>
				<input type="text" name="city" id="City" />
	
				<label for="Email">Email:</label>
				<input type="text" name="email" id="Email" />
				
				<label for="Message">Message:</label><br />
				<textarea name="message" rows="20" cols="20" id="Message"></textarea>

				<input type="submit" name="submit" value="Submit" class="submit-button" />
			</form>
			
			<div style="clear: both;"></div>
			
	</div>
	
	</div>

</body>

</html>